---
  # - name: upgrade all packages
  #   yum: name=* state=latest

  - name: install required packages
    yum: name={{item}} state=present
    with_items:
    - epel-release
    - vim
    - net-tools
    - telnet
    - nc
    - bind-utils
    - git
    - tmux
    - mlocate
    - wget
    - httpd
    - php
    - gcc
    - glibc
    - glibc-common
    - gd
    - gd-devel
    - make
    - net-snmp
    - python-pip
    sudo: yes


  - name: install python libraries
    pip: name={{item}}
    with_items:
    - passlib
    sudo: yes
