---
  - name: add rules to SELinux
    shell: chcon -R -t httpd_sys_content_t {{home.nagios}} && chcon -R -t httpd_sys_script_rw_t {{home.nagios}}/var/rw
    sudo: yes

  - name: start nagios
    service:
      name: nagios
      state: started
      enabled: yes
      runlevel: 35
    sudo: yes

  - name: start apache
    service:
      name: httpd
      state: started
      enabled: yes
      runlevel: 35
    sudo: yes
